# Generated by Django 5.2.1 on 2025-06-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('termino_busqueda', models.CharField(max_length=255)),
                ('fecha_busqueda', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
