# Generated by Django 5.2.1 on 2025-06-29 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenido_infrastructure', '0001_initial'),
        ('etiqueta_infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_etiquetas', to='contenido_infrastructure.contenido')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_contenido', to='etiqueta_infrastructure.etiqueta')),
            ],
            options={
                'unique_together': {('contenido', 'etiqueta')},
            },
        ),
    ]
