# Generated by Django 5.2.1 on 2025-06-29 09:11

import Backend.WantMusic.Contenido.infrastructure.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('archivo', models.FileField(upload_to=Backend.WantMusic.Contenido.infrastructure.models.ruta_personalizada)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subido_por_id', models.IntegerField(blank=True, null=True)),
                ('artista', models.CharField(blank=True, max_length=255, null=True)),
                ('eliminado', models.BooleanField(default=False)),
            ],
        ),
    ]
