# Generated by Django 5.2.1 on 2025-07-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido_infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='archivo',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
    ]
