# Generated by Django 5.2.1 on 2025-06-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoEliminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido_id', models.IntegerField()),
                ('fecha_eliminacion', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('eliminado_por_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
