# Generated by Django 5.2.1 on 2025-06-29 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidoEliminado_infrastructure', '0001_initial'),
        ('contenido_infrastructure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenidoeliminado',
            name='contenido_id',
        ),
        migrations.RemoveField(
            model_name='contenidoeliminado',
            name='eliminado_por_id',
        ),
        migrations.AddField(
            model_name='contenidoeliminado',
            name='contenido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenido_infrastructure.contenido'),
        ),
        migrations.AddField(
            model_name='contenidoeliminado',
            name='eliminado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
